name: Auto upload to tencent COS

on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3
      
      - name: Auto upload to tencent COS
        run: |
          pip install coscmd
          coscmd config -a ${{ secrets.SECRET_ID }} -s ${{ secrets.SECRET_KEY }} -b ${{ secrets.BUCKET }} -r ap-chengdu -m 30
          coscmd upload -rs ./ / --ignore "./.git/*","./.github/*"
          coscmd abort
